title:              my blog
email:              me@marioanton.com
description:        A Blog Testing 
author:             mario anton 
baseurl:            "/"
url:                "https://blackrockdigital.github.io"

# Social Profiles
twitter_username:   marioanton
github_username:    marioanton
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-29706858-10 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
